added serializer method for vector of bools
- based on changes in commit druxx/eudaq@a1bbb185810457694bd07f48bc28bad1b1613c54
- fixes compiler error on Clang 4.2 (LLVN svn 3.2):
[ 53%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/StandardEvent.cc.o
In file included from /Users/hanno/src/eudaq/main/lib/src/StandardEvent.cc:1:
In file included from /Users/hanno/src/eudaq/./main/include/eudaq/StandardEvent.hh:4:
In file included from /Users/hanno/src/eudaq/./main/include/eudaq/Event.hh:11:
/Users/hanno/src/eudaq/./main/include/eudaq/Serializer.hh:99:23: error: no matching member function for call to 'GetFunc'
      WriteHelper<T>::GetFunc(static_cast<T*>(0))(*this, v);
      ~~~~~~~~~~~~~~~~^~~~~~~
/Users/hanno/src/eudaq/./main/include/eudaq/Serializer.hh:119:9: note: in instantiation of function template specialization
      'eudaq::Serializer::write<std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > > >' requested here
        write(t[i]);
        ^
/Users/hanno/src/eudaq/./main/include/eudaq/Serializer.hh:119:9: note: in instantiation of function template specialization
      'eudaq::Serializer::write<bool>' requested here
        write(t[i]);
        ^
/Users/hanno/src/eudaq/main/lib/src/StandardEvent.cc:43:9: note: in instantiation of function template specialization
      'eudaq::Serializer::write<std::__1::vector<bool, std::__1::allocator<bool> > >' requested here
    ser.write(m_pivot);
        ^
/Users/hanno/src/eudaq/./main/include/eudaq/Serializer.hh:44:21: note: candidate function not viable: no known conversion from
      'std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > > *' to 'eudaq::Serializable *' for 1st argument
      static writer GetFunc(Serializable *) { return write_ser; }
                    ^
/Users/hanno/src/eudaq/./main/include/eudaq/Serializer.hh:45:21: note: candidate function not viable: no known conversion from
      'std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > > *' to 'float *' for 1st argument
      static writer GetFunc(float *) { return write_float; }
                    ^
/Users/hanno/src/eudaq/./main/include/eudaq/Serializer.hh:46:21: note: candidate function not viable: no known conversion from
      'std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > > *' to 'double *' for 1st argument
      static writer GetFunc(double *) { return write_double; }
                    ^
/Users/hanno/src/eudaq/./main/include/eudaq/Serializer.hh:47:21: note: candidate function not viable: no known conversion from
      'std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > > *' to 'bool *' for 1st argument
      static writer GetFunc(bool * ) { return write_char; }
                    ^
/Users/hanno/src/eudaq/./main/include/eudaq/Serializer.hh:48:21: note: candidate function not viable: no known conversion from
      'std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > > *' to 'uint8_t *' (aka 'unsigned char *') for
      1st argument
      static writer GetFunc(uint8_t * ) { return write_char; }
                    ^
/Users/hanno/src/eudaq/./main/include/eudaq/Serializer.hh:49:21: note: candidate function not viable: no known conversion from
      'std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > > *' to 'int8_t *' (aka 'signed char *') for 1st
      argument
      static writer GetFunc(int8_t *  ) { return write_char; }
                    ^
/Users/hanno/src/eudaq/./main/include/eudaq/Serializer.hh:50:21: note: candidate function not viable: no known conversion from
      'std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > > *' to 'uint16_t *' (aka 'unsigned short *') for
      1st argument
      static writer GetFunc(uint16_t *) { return write_int; }
                    ^
/Users/hanno/src/eudaq/./main/include/eudaq/Serializer.hh:51:21: note: candidate function not viable: no known conversion from
      'std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > > *' to 'int16_t *' (aka 'short *') for 1st
      argument
      static writer GetFunc(int16_t * ) { return write_int; }
                    ^
/Users/hanno/src/eudaq/./main/include/eudaq/Serializer.hh:52:21: note: candidate function not viable: no known conversion from
      'std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > > *' to 'uint32_t *' (aka 'unsigned int *') for
      1st argument
      static writer GetFunc(uint32_t *) { return write_int; }
                    ^
/Users/hanno/src/eudaq/./main/include/eudaq/Serializer.hh:53:21: note: candidate function not viable: no known conversion from
      'std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > > *' to 'int32_t *' (aka 'int *') for 1st argument
      static writer GetFunc(int32_t * ) { return write_int; }
                    ^
/Users/hanno/src/eudaq/./main/include/eudaq/Serializer.hh:54:21: note: candidate function not viable: no known conversion from
      'std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > > *' to 'uint64_t *' (aka 'unsigned long long *')
      for 1st argument
      static writer GetFunc(uint64_t *) { return write_int; }
                    ^
/Users/hanno/src/eudaq/./main/include/eudaq/Serializer.hh:55:21: note: candidate function not viable: no known conversion from
      'std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > > *' to 'int64_t *' (aka 'long long *') for 1st
      argument
      static writer GetFunc(int64_t * ) { return write_int; }
                    ^
1 error generated.