fixes compilation error on GCC 4.7 with Qt 4.8.3
error message:
In file included from /usr/include/qt4/QtCore/qvariant.h:48:0,
                 from /usr/include/qt4/QtCore/qabstractitemmodel.h:45,
                 from /usr/include/qt4/QtCore/QAbstractListModel:1,
                 from /home/hperrey/src/eudaq/gui/./include/RunControlModel.hh:4,
                 from /home/hperrey/src/eudaq/gui/src/RunControlModel.cc:2:
/usr/include/qt4/QtCore/qmetatype.h: In instantiation of ‘static int QMetaTypeId2<T>::qt_metatype_id() [with T = QVector<int>]’:
/usr/include/qt4/QtCore/qmetatype.h:230:44:   required from ‘int qMetaTypeId(T*) [with T = QVector<int>]’
/usr/include/qt4/QtCore/qmetatype.h:243:29:   required from ‘int qRegisterMetaType(T*) [with T = QVector<int>]’
/home/hperrey/src/eudaq/gui/src/RunControlModel.cc:50:35:   required from here
/usr/include/qt4/QtCore/qmetatype.h:169:80: error: ‘qt_metatype_id’ is not a member of ‘QMetaTypeId<QVector<int> >’